from flask import Blueprint, request, jsonify
from pydantic import ValidationError
from api.models.schemas import PatientInput, RecommendationResponse, Recommendation
from api.services.extractor import extract_conditions
from api.services.retriever import retrieve
from api.services.recommender import generate_recommendations

# A Blueprint is Flask's way of grouping related routes.
# The first argument is the blueprint's internal name.
# url_prefix means all routes in this blueprint start with /api.
recommend_bp = Blueprint('recommend', __name__, url_prefix='/api')

DISCLAIMER = (
    'These recommendations are generated by an AI system for informational purposes only. '
    'They are not a substitute for professional medical advice, diagnosis, or treatment. '
    'Always consult a qualified healthcare provider before making changes to your diet, '
    'exercise, or supplement regimen.'
)


@recommend_bp.route('/recommend', methods=['POST'])
def recommend():
    # ── 1. Parse and validate the request body ────────────────────────
    # request.get_json() parses the JSON body into a Python dict.
    # PatientInput(**data) passes it to Pydantic for validation.
    # If raw_text is missing or empty, Pydantic raises ValidationError.
    try:
        data = PatientInput(**request.get_json(force=True))
    except ValidationError as e:
        return jsonify({'error': 'Invalid input', 'details': e.errors()}), 422
    except Exception:
        return jsonify({'error': 'Could not parse request body as JSON'}), 400

    # ── 2. Extract conditions ─────────────────────────────────────────
    # First LLM call: identify what conditions the patient has.
    try:
        conditions = extract_conditions(data.raw_text)
    except Exception as e:
        return jsonify({'error': f'Condition extraction failed: {str(e)}'}), 500

    if not conditions:
        return jsonify({'error': 'Could not identify any medical conditions in the provided text'}), 422

    # ── 3. Retrieve relevant document chunks ─────────────────────────
    # For each condition, retrieve the top 3 most relevant chunks.
    # We use top_k=3 per condition to avoid sending too many tokens to the LLM.
    all_chunks = []
    for condition in conditions:
        chunks = retrieve(condition, top_k=3)
        all_chunks.extend(chunks)

    # Deduplicate chunks by content (the same chunk might match multiple conditions)
    seen_content = set()
    unique_chunks = []
    for chunk in all_chunks:
        if chunk['content'] not in seen_content:
            seen_content.add(chunk['content'])
            unique_chunks.append(chunk)

    # ── 4. Generate recommendations ───────────────────────────────────
    # Second LLM call: generate structured output from the retrieved evidence.
    try:
        raw_output = generate_recommendations(conditions, unique_chunks, data.raw_text)
    except Exception as e:
        return jsonify({'error': f'Recommendation generation failed: {str(e)}'}), 500

    # ── 5. Validate output and return ─────────────────────────────────
    # Pass the LLM output through Pydantic to validate it matches our schema.
    # If the LLM returned malformed JSON, this will raise ValidationError.
    try:
        validated = RecommendationResponse(
            inferred_conditions=conditions,
            recommendations=[Recommendation(**r) for r in raw_output.get('recommendations', [])],
            disclaimer=DISCLAIMER,
        )
    except (ValidationError, KeyError) as e:
        return jsonify({'error': 'LLM returned unexpected output format', 'raw': raw_output}), 500

    return jsonify(validated.model_dump()), 200

